version: '3.8'
services:
  litmus-db:
    image: postgres:14-alpine
    container_name: litmus-db-dev
    environment:
      POSTGRES_USER: litmus
      POSTGRES_PASSWORD: litmus_dev_pass
      POSTGRES_DB: litmus_db
    ports:
      - '5432:5432'
    volumes:
      - litmus_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  litmus-cache:
    image: redis:7-alpine
    container_name: litmus-cache-dev
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  litmus_pg_data:
